### ISSUE TITLE
[InvalidArgumentException] Could not find a matching version of package oanhnn/laravel-aws. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).   

### ISSUE THREAD

**Issue by rajarshi1** [oanhnn/laravel-aws#1]
I tried running - **composer require oanhnn/laravel-aws** but it returned an [InvalidArgumentException] such as above. Please advice. @oanhnn 

![Screenshot from 2020-11-12 17-30-20](https://user-images.githubusercontent.com/19686787/98939133-f67ba400-250e-11eb-90e3-78f4031b6f84.png)

**Comment by oanhnn** [comment]
This package is never release yet. Please use another package.
I will continue develop it, but not now.
I am sorry :see_no_evil:

**Comment by rajarshi1** [comment]
Ah ok. I thought as much! No problem, thank you for the clarification. @oanhnn

**Comment by tauseedzaman** [comment]
Hi, is at still in development

**Comment by rajarshi1** [comment]
hey @tauseedzaman, as @oanhnn said, this package is not released, please use another one.

**Comment by tauseedzaman** [comment]
ok
